### ISSUE TITLE
Publicar o add-on

### ISSUE THREAD

**Issue by soapdog** [guilhermemarconi/adblock-blocker-unblock#1]
Faltou publicar em addons.mozilla.com 😸

**Comment by guilhermemarconi** [comment]
Eu publiquei! Mas tive problema com direitos autorais. Recebi um e-mail da
galera que detém os direitos do nome AdBlock e pediram pra eu tirar. :/

Em 10 de ago de 2017 16:09, "Andre Alves Garzia" <notifications@github.com>
escreveu:

**Comment by guilhermemarconi** [comment]
É! Mas aí eu ainda não fiz ahahahahaha

2017-08-16 12:29 GMT-03:00 Andre Alves Garzia <notifications@github.com>:

**Comment by guilhermemarconi** [comment]
Pronto!
Mozilla: https://addons.mozilla.org/en-US/firefox/addon/remove-block-anncios-abril/
Chrome: https://chrome.google.com/webstore/detail/remove-bloqueador-de-an%C3%BAn/gapdehheiilebacamgbmkbjbplibciic
